### ISSUE TITLE
Currently not hiding node_modules dir

### ISSUE THREAD

**Issue by lil5** [ChrisBibby/vscode_hide-node-modules#114]
If I click on the 'Node_Modules' button on the status bar it used to hide / unhide the node_modules in the explorer.

Currently this does not happen anymore.

VSCode version: 1.59.1

**Comment by ChrisBibby** [comment]
Hi, 

Currently using the extension on the same version of VSCode on a number of machines and not experienced this issue.

Have you tried fully uninstalling the extension, restarting VSCode and installing again?  It could also be another extension conflicting.

One thing you could try, VSCode creates a .vscode folder within your projects to store settings, the extension adds a value to the settings.json file within that folder.  When you try to switch the visibiity of node_modules, does the setting 'files.exclude' change at all?

**Comment by lil5** [comment]
Having reopened vscode the next day it has been resolved. 

I don't know how the error occurred, (it may have been some vim extension I was playing around with but that is pure speculation) nevertheless it seems to have fixed itself.
