### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by kennedybaird** [ChrisBibby/vscode_hide-node-modules#619]
It seems there's a memory leak or something really intensive happening with large monorepo(s).

I was working with [keystone](https://github.com/keystonejs/keystone), and my CPU was spiking to ~40%, and memory was climbing up to 3GB before VSCode would crash.

After disabling all extensions, re-enabling one by one, it seems this extension was potentially the reason.

To replicate, you might be able to simply:

- make a new vscode profile with just this extension
- clone the above repo
- run vscode, opening this folder

When I did the above I received "reason: crashed, code: 135":
![image](https://github.com/user-attachments/assets/5574206f-b25c-4fea-9327-4cc627afad00)

**Comment by ChrisBibby** [comment]
I'm unable to replicate your issue.  I understand that repo is large but opening it up on my machines and I've not seen any issues. Tried on both Mac and WIndows using the latest VSCode (v1.92.2) and I've not seen any abnormal CPU spikes or memory usage.  I don't have access to a Linux box to test it with.

Right now all I can suggest is make sure you're running the latest VSCode.  Without any kind of logs or stack traces I don't have a lot to go on.  There are a bunch of Github issues for Code 135 on the VSCode repo that people have reported - not sure what the specific cause is or if its a generic error code. 

Sorry I couldn't be of more help.
