### ISSUE TITLE
The context menu is not visible

### ISSUE THREAD

**Issue by butcher51** [ChrisBibby/vscode_hide-node-modules#65]
Hi!

I wrote a comment for you here ( https://marketplace.visualstudio.com/items?itemName=chrisbibby.hide-node-modules&ssr=false#review-details ) yesterday but I can't write replay on this site so searched for the repo instead :)

So the problem as I mentioned I can't see the new context menu item. The problem maybe there is multiple package.json in our project, and there is no package.json in the root folder.

**Comment by ChrisBibby** [comment]
Can you see the status bar item, the command palette option?

**Comment by ChrisBibby** [comment]
New version (0.0.8) should fix this. If you could let me know if that works.  

Thanks for reporting 👍

**Comment by butcher51** [comment]
Great, it's working! Thank you very much! :)
